// seed.mjs — DEPRECATED: use seed_listings_nynj.sql instead.
// This file contains old CA/FL data and is no longer used.
// The current seed is seed_listings_nynj.sql (60 NY/NJ listings).
//
// Original: inserted 50 CA/FL apartment listings via JS.

import { createClient } from "@supabase/supabase-js";

// Read credentials from environment — never hardcode keys in source.
// Usage: SUPABASE_URL=https://xxx.supabase.co SUPABASE_KEY=sb_xxx node seed.mjs
const supabase = createClient(
  process.env.SUPABASE_URL  || "",
  process.env.SUPABASE_KEY  || ""
);

// Variety of real apartment-style Unsplash images
const IMAGES = [
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=800&q=80",
];

const img = (i) => IMAGES[i % IMAGES.length];

const listings = [
  // ── CALIFORNIA ────────────────────────────────────────────────────────
  {
    title: "Modern Studio in Silver Lake",
    description: "Bright, newly renovated studio in the heart of Silver Lake. Exposed brick, polished concrete floors, and a private deck overlooking the hills. Walking distance to Sunset Junction shops and cafés.",
    address: "2847 Sunset Blvd",
    city: "Los Angeles", state: "California", zip: "90026",
    price: 1950, bedrooms: 0, bathrooms: 1, sqft: 520,
    latitude: 34.0768, longitude: -118.2617,
    image_url: img(0),
    amenities: ["Air Conditioning", "Hardwood Floors", "Dishwasher", "Parking", "Laundry in Building"],
  },
  {
    title: "Spacious 2BR in West Hollywood",
    description: "Sun-drenched two-bedroom apartment with floor-to-ceiling windows and an open-concept kitchen. Steps from the Sunset Strip, boutique gyms, and world-class restaurants.",
    address: "1120 N Clark St",
    city: "Los Angeles", state: "California", zip: "90069",
    price: 3400, bedrooms: 2, bathrooms: 2, sqft: 1080,
    latitude: 34.0900, longitude: -118.3617,
    image_url: img(1),
    amenities: ["Pool", "Gym", "Rooftop Deck", "In-Unit Washer/Dryer", "Air Conditioning", "Parking"],
  },
  {
    title: "Luxury High-Rise 1BR in Downtown LA",
    description: "Stunning panoramic city views from the 22nd floor. Floor-to-ceiling windows, chef's kitchen with quartz counters, and resort-style amenities including a rooftop infinity pool.",
    address: "888 S Olive St",
    city: "Los Angeles", state: "California", zip: "90014",
    price: 3100, bedrooms: 1, bathrooms: 1, sqft: 760,
    latitude: 34.0441, longitude: -118.2566,
    image_url: img(2),
    amenities: ["Pool", "Gym", "Concierge", "Rooftop Deck", "In-Unit Washer/Dryer", "Parking", "Air Conditioning"],
  },
  {
    title: "Charming 3BR Bungalow in Culver City",
    description: "Renovated 1940s bungalow with original hardwood floors and a large private backyard. Fully updated kitchen and bathrooms, two-car garage, and mature fruit trees.",
    address: "4215 Washington Blvd",
    city: "Los Angeles", state: "California", zip: "90232",
    price: 4800, bedrooms: 3, bathrooms: 2, sqft: 1620,
    latitude: 34.0012, longitude: -118.3965,
    image_url: img(3),
    amenities: ["Hardwood Floors", "In-Unit Washer/Dryer", "Parking", "Backyard", "Pet Friendly", "Air Conditioning"],
  },
  {
    title: "Cozy 1BR Near UCLA",
    description: "Well-maintained one-bedroom apartment just four blocks from UCLA campus. Quiet building with a courtyard garden, secure entry, and on-site laundry.",
    address: "671 Gayley Ave",
    city: "Los Angeles", state: "California", zip: "90024",
    price: 2350, bedrooms: 1, bathrooms: 1, sqft: 640,
    latitude: 34.0617, longitude: -118.4487,
    image_url: img(4),
    amenities: ["Laundry in Building", "Courtyard", "Dishwasher", "Air Conditioning", "Bike Storage"],
  },
  {
    title: "Victorian Flat in the Mission",
    description: "Stunning top-floor Victorian flat with 12-foot ceilings, original bay windows, and restored moldings. Updated kitchen, in-unit laundry, and a private deck with city views.",
    address: "3312 22nd St",
    city: "San Francisco", state: "California", zip: "94110",
    price: 3850, bedrooms: 2, bathrooms: 1, sqft: 1100,
    latitude: 37.7553, longitude: -122.4195,
    image_url: img(5),
    amenities: ["In-Unit Washer/Dryer", "Hardwood Floors", "Dishwasher", "Deck", "Bike Storage", "Pet Friendly"],
  },
  {
    title: "Modern Condo in SoMa",
    description: "Sleek one-bedroom condo in the heart of SoMa. Open floor plan, chef's kitchen, and a private balcony. Building amenities include a fitness center, bike room, and doorman.",
    address: "255 King St",
    city: "San Francisco", state: "California", zip: "94107",
    price: 4200, bedrooms: 1, bathrooms: 1, sqft: 780,
    latitude: 37.7785, longitude: -122.3948,
    image_url: img(6),
    amenities: ["Gym", "Doorman", "Concierge", "Balcony", "In-Unit Washer/Dryer", "Parking"],
  },
  {
    title: "Sunny Studio in the Castro",
    description: "Bright south-facing studio in a classic Castro building. Hardwood floors, updated kitchen, and steps from the J-Church MUNI line. Perfect for young professionals.",
    address: "492 Castro St",
    city: "San Francisco", state: "California", zip: "94114",
    price: 2200, bedrooms: 0, bathrooms: 1, sqft: 490,
    latitude: 37.7609, longitude: -122.4350,
    image_url: img(7),
    amenities: ["Hardwood Floors", "Laundry in Building", "Dishwasher", "Bike Storage"],
  },
  {
    title: "Pacific Heights 2BR with Views",
    description: "Beautiful two-bedroom apartment on the top floor of a Edwardian building. Sweeping views of the Bay and Golden Gate Bridge. Period details throughout with modern updates.",
    address: "2734 Clay St",
    city: "San Francisco", state: "California", zip: "94115",
    price: 5500, bedrooms: 2, bathrooms: 2, sqft: 1350,
    latitude: 37.7887, longitude: -122.4402,
    image_url: img(8),
    amenities: ["Hardwood Floors", "In-Unit Washer/Dryer", "Parking", "Fireplace", "Bay Views"],
  },
  {
    title: "Gaslamp Quarter Studio",
    description: "Stylish studio loft in a converted warehouse steps from the Gaslamp Quarter. Exposed brick, 14-foot ceilings, and industrial finishes. Walkable to Petco Park and the waterfront.",
    address: "755 6th Ave",
    city: "San Diego", state: "California", zip: "92101",
    price: 2050, bedrooms: 0, bathrooms: 1, sqft: 540,
    latitude: 32.7087, longitude: -117.1592,
    image_url: img(9),
    amenities: ["Air Conditioning", "Hardwood Floors", "Rooftop Deck", "Gym", "Bike Storage"],
  },
  {
    title: "Beach-Close 1BR in Pacific Beach",
    description: "Breezy one-bedroom apartment three blocks from the sand. Sunny balcony, updated kitchen, and an outdoor community deck with BBQ grills. Walk to restaurants on Garnet Ave.",
    address: "1847 Chalcedony St",
    city: "San Diego", state: "California", zip: "92109",
    price: 2600, bedrooms: 1, bathrooms: 1, sqft: 690,
    latitude: 32.7939, longitude: -117.2374,
    image_url: img(0),
    amenities: ["Balcony", "Air Conditioning", "Laundry in Building", "Parking", "BBQ Area", "Pet Friendly"],
  },
  {
    title: "Mission Hills 2BR with Yard",
    description: "Charming lower duplex unit in quiet Mission Hills with a large private patio. Newly remodeled kitchen and bathrooms, hardwood floors, and a one-car garage.",
    address: "3826 Hawk St",
    city: "San Diego", state: "California", zip: "92103",
    price: 3200, bedrooms: 2, bathrooms: 1, sqft: 1020,
    latitude: 32.7397, longitude: -117.1744,
    image_url: img(1),
    amenities: ["Hardwood Floors", "Parking", "Patio", "In-Unit Washer/Dryer", "Pet Friendly", "Air Conditioning"],
  },
  {
    title: "Midtown Sacramento 1BR",
    description: "Newly renovated one-bedroom in Midtown Sacramento's vibrant arts district. Quartz countertops, stainless appliances, and in-unit laundry. Steps from the Farm-to-Fork dining corridor.",
    address: "1916 P St",
    city: "Sacramento", state: "California", zip: "95811",
    price: 1750, bedrooms: 1, bathrooms: 1, sqft: 680,
    latitude: 38.5669, longitude: -121.4822,
    image_url: img(2),
    amenities: ["In-Unit Washer/Dryer", "Air Conditioning", "Stainless Steel Appliances", "Parking", "Pet Friendly"],
  },
  {
    title: "Downtown Sacramento 2BR Tower",
    description: "High-floor two-bedroom in a modern downtown high-rise. City views, resort-style pool and spa, fitness center, and secure parking. Minutes from the Golden 1 Center.",
    address: "500 J St",
    city: "Sacramento", state: "California", zip: "95814",
    price: 2900, bedrooms: 2, bathrooms: 2, sqft: 1150,
    latitude: 38.5816, longitude: -121.5005,
    image_url: img(3),
    amenities: ["Pool", "Gym", "Concierge", "Rooftop Deck", "In-Unit Washer/Dryer", "Parking", "Air Conditioning"],
  },
  {
    title: "San Jose Tech Corridor 1BR",
    description: "Modern apartment in the heart of San Jose's tech corridor. Smart home features, EV charging, and resort-style amenities. Shuttle stop to major tech campuses.",
    address: "188 W Santa Clara St",
    city: "San Jose", state: "California", zip: "95113",
    price: 2950, bedrooms: 1, bathrooms: 1, sqft: 740,
    latitude: 37.3327, longitude: -121.8924,
    image_url: img(4),
    amenities: ["Gym", "Pool", "EV Charging", "In-Unit Washer/Dryer", "Rooftop Deck", "Bike Storage", "Air Conditioning"],
  },
  {
    title: "Oakland Uptown 2BR Loft",
    description: "Industrial-chic loft in Oakland's Uptown arts district. Exposed concrete, 13-foot ceilings, and giant south-facing windows. Walk to BART, galleries, and nightlife.",
    address: "2323 Broadway",
    city: "Oakland", state: "California", zip: "94612",
    price: 2700, bedrooms: 2, bathrooms: 2, sqft: 1180,
    latitude: 37.8112, longitude: -122.2716,
    image_url: img(5),
    amenities: ["Hardwood Floors", "In-Unit Washer/Dryer", "Bike Storage", "Rooftop Deck", "Air Conditioning", "Pet Friendly"],
  },
  {
    title: "Temescal 1BR with Garage",
    description: "Cute one-bedroom in Temescal with a private one-car garage and small patio. Updated kitchen with white shaker cabinets, original hardwood floors, and walking distance to excellent dining.",
    address: "4819 Shafter Ave",
    city: "Oakland", state: "California", zip: "94609",
    price: 2250, bedrooms: 1, bathrooms: 1, sqft: 720,
    latitude: 37.8388, longitude: -122.2642,
    image_url: img(6),
    amenities: ["Hardwood Floors", "Parking", "Patio", "In-Unit Washer/Dryer", "Pet Friendly"],
  },
  {
    title: "Belmont Shore Beachside 2BR",
    description: "Airy two-bedroom two blocks from the beach in coveted Belmont Shore. Vaulted ceilings, updated baths, and a community rooftop deck with ocean views.",
    address: "248 Prospect Ave",
    city: "Long Beach", state: "California", zip: "90803",
    price: 2950, bedrooms: 2, bathrooms: 2, sqft: 980,
    latitude: 33.7497, longitude: -118.1302,
    image_url: img(7),
    amenities: ["Rooftop Deck", "Air Conditioning", "Laundry in Building", "Parking", "Pet Friendly"],
  },
  {
    title: "Anaheim Resort District Studio",
    description: "Fully furnished studio near the Anaheim Resort District. Ideal for travel nurses or contractors. Includes utilities, Wi-Fi, and weekly cleaning service.",
    address: "1510 S Harbor Blvd",
    city: "Anaheim", state: "California", zip: "92802",
    price: 1800, bedrooms: 0, bathrooms: 1, sqft: 450,
    latitude: 33.8091, longitude: -117.9238,
    image_url: img(8),
    amenities: ["Pool", "Air Conditioning", "Furnished", "Parking", "Gym"],
  },
  {
    title: "Pasadena Old Town 1BR",
    description: "Elegant one-bedroom in a restored 1920s building in Old Town Pasadena. Original crown molding, refinished hardwood floors, and a gourmet kitchen. Walk score 95.",
    address: "88 E Colorado Blvd",
    city: "Pasadena", state: "California", zip: "91105",
    price: 2450, bedrooms: 1, bathrooms: 1, sqft: 760,
    latitude: 34.1448, longitude: -118.1503,
    image_url: img(9),
    amenities: ["Hardwood Floors", "Dishwasher", "Air Conditioning", "Laundry in Building", "Bike Storage"],
  },
  {
    title: "Santa Monica 3BR Family Apartment",
    description: "Rare three-bedroom apartment just six blocks from Santa Monica Beach. Bright and airy with a large living area, updated kitchen, and two full baths. Tandem parking included.",
    address: "1347 5th St",
    city: "Santa Monica", state: "California", zip: "90401",
    price: 6200, bedrooms: 3, bathrooms: 2, sqft: 1580,
    latitude: 34.0195, longitude: -118.4912,
    image_url: img(0),
    amenities: ["In-Unit Washer/Dryer", "Parking", "Air Conditioning", "Dishwasher", "Pet Friendly"],
  },
  {
    title: "Berkeley Hills 2BR with Views",
    description: "Stunning hillside two-bedroom with breathtaking views of the Bay and San Francisco skyline. Deck, fireplace, and a private garden. Minutes from UC Berkeley campus.",
    address: "2845 Hillegass Ave",
    city: "Berkeley", state: "California", zip: "94705",
    price: 3600, bedrooms: 2, bathrooms: 1, sqft: 1050,
    latitude: 37.8598, longitude: -122.2542,
    image_url: img(1),
    amenities: ["Fireplace", "Deck", "Hardwood Floors", "Laundry in Building", "Pet Friendly", "Bay Views"],
  },
  {
    title: "Irvine Village 2BR",
    description: "Immaculate two-bedroom apartment in Irvine's master-planned village. Resort-style pools, tennis courts, and excellent schools. Attached two-car garage and private patio.",
    address: "14 Sagebrush",
    city: "Irvine", state: "California", zip: "92620",
    price: 3100, bedrooms: 2, bathrooms: 2, sqft: 1200,
    latitude: 33.7175, longitude: -117.7981,
    image_url: img(2),
    amenities: ["Pool", "Gym", "Tennis Court", "Parking", "In-Unit Washer/Dryer", "Air Conditioning", "Pet Friendly"],
  },
  {
    title: "Chula Vista 1BR Near Trolley",
    description: "Move-in ready one-bedroom near the Blue Line Trolley in Chula Vista. Stainless appliances, new carpet, and a private balcony. Community pool and BBQ area.",
    address: "680 Third Ave",
    city: "Chula Vista", state: "California", zip: "91910",
    price: 1850, bedrooms: 1, bathrooms: 1, sqft: 650,
    latitude: 32.6401, longitude: -117.0842,
    image_url: img(3),
    amenities: ["Pool", "Balcony", "Air Conditioning", "BBQ Area", "Laundry in Building", "Parking"],
  },
  {
    title: "Nob Hill Studio with Character",
    description: "Cozy studio in a classic Nob Hill building. High ceilings, bay window with cable car views, and a walk-in closet. Doorman building with on-site laundry.",
    address: "1050 California St",
    city: "San Francisco", state: "California", zip: "94108",
    price: 2400, bedrooms: 0, bathrooms: 1, sqft: 480,
    latitude: 37.7924, longitude: -122.4135,
    image_url: img(4),
    amenities: ["Doorman", "Hardwood Floors", "Laundry in Building", "Dishwasher", "Cable Car Views"],
  },

  // ── FLORIDA ──────────────────────────────────────────────────────────
  {
    title: "Brickell Luxury 1BR with Bay View",
    description: "Stunning one-bedroom in Miami's Financial District with direct Biscayne Bay views. Floor-to-ceiling impact glass, Italian kitchen, and access to a resort-style amenity deck with infinity pool.",
    address: "1300 Brickell Bay Dr",
    city: "Miami", state: "Florida", zip: "33131",
    price: 3800, bedrooms: 1, bathrooms: 1, sqft: 820,
    latitude: 25.7596, longitude: -80.1918,
    image_url: img(5),
    amenities: ["Pool", "Gym", "Concierge", "Valet Parking", "In-Unit Washer/Dryer", "Bay Views", "Air Conditioning"],
  },
  {
    title: "Wynwood Art District 2BR Loft",
    description: "Converted warehouse loft in Miami's celebrated Wynwood art district. 16-foot ceilings, polished concrete floors, and direct access to the building's rooftop terrace with murals.",
    address: "2750 NW 3rd Ave",
    city: "Miami", state: "Florida", zip: "33127",
    price: 3200, bedrooms: 2, bathrooms: 2, sqft: 1280,
    latitude: 25.7987, longitude: -80.2016,
    image_url: img(6),
    amenities: ["Rooftop Deck", "In-Unit Washer/Dryer", "Air Conditioning", "Bike Storage", "Pet Friendly"],
  },
  {
    title: "South Beach Art Deco 1BR",
    description: "Iconic Art Deco building steps from Ocean Drive. Beautifully restored one-bedroom with terrazzo floors and original jalousie windows. Courtyard pool and lounge chairs included.",
    address: "1001 Collins Ave",
    city: "Miami", state: "Florida", zip: "33139",
    price: 2900, bedrooms: 1, bathrooms: 1, sqft: 700,
    latitude: 25.7795, longitude: -80.1303,
    image_url: img(7),
    amenities: ["Pool", "Air Conditioning", "Laundry in Building", "Doorman", "Beach Access"],
  },
  {
    title: "Coral Gables 3BR Family Home",
    description: "Elegant three-bedroom apartment in historic Coral Gables. Mediterranean-style architecture, large private patio, mature landscaping, and walking distance to the Miracle Mile shopping district.",
    address: "3440 Segovia St",
    city: "Miami", state: "Florida", zip: "33134",
    price: 4600, bedrooms: 3, bathrooms: 2, sqft: 1780,
    latitude: 25.7216, longitude: -80.2683,
    image_url: img(8),
    amenities: ["Patio", "In-Unit Washer/Dryer", "Parking", "Air Conditioning", "Pet Friendly", "Dishwasher"],
  },
  {
    title: "Downtown Orlando Studio",
    description: "Modern studio in a boutique high-rise steps from Lake Eola. Floor-to-ceiling windows, custom closets, and a smart thermostat. Building amenities include a gym and sky lounge.",
    address: "215 E Central Blvd",
    city: "Orlando", state: "Florida", zip: "32801",
    price: 1700, bedrooms: 0, bathrooms: 1, sqft: 510,
    latitude: 28.5414, longitude: -81.3755,
    image_url: img(9),
    amenities: ["Gym", "Sky Lounge", "In-Unit Washer/Dryer", "Air Conditioning", "Bike Storage"],
  },
  {
    title: "College Park 2BR Bungalow",
    description: "Adorable Craftsman bungalow in Orlando's walkable College Park neighborhood. Updated kitchen with butcher block counters, original hardwood floors, and a screened back porch.",
    address: "2108 Edgewater Dr",
    city: "Orlando", state: "Florida", zip: "32804",
    price: 2400, bedrooms: 2, bathrooms: 1, sqft: 1050,
    latitude: 28.5732, longitude: -81.3826,
    image_url: img(0),
    amenities: ["Hardwood Floors", "Screened Porch", "In-Unit Washer/Dryer", "Air Conditioning", "Pet Friendly"],
  },
  {
    title: "Lake Nona Medical City 1BR",
    description: "Brand new apartment in Lake Nona's Medical City campus. Perfect for healthcare workers and researchers. Attached garage, resort pool, and complimentary shuttle to the hospital.",
    address: "6807 Tavistock Lakes Blvd",
    city: "Orlando", state: "Florida", zip: "32827",
    price: 2100, bedrooms: 1, bathrooms: 1, sqft: 780,
    latitude: 28.3722, longitude: -81.2482,
    image_url: img(1),
    amenities: ["Pool", "Gym", "Parking", "In-Unit Washer/Dryer", "Air Conditioning", "EV Charging"],
  },
  {
    title: "Hyde Park 1BR Near Bayshore",
    description: "Charming one-bedroom in Tampa's Hyde Park neighborhood, two blocks from Bayshore Boulevard. Updated kitchen, hardwood floors, and a covered private patio.",
    address: "814 S Willow Ave",
    city: "Tampa", state: "Florida", zip: "33606",
    price: 2000, bedrooms: 1, bathrooms: 1, sqft: 730,
    latitude: 27.9395, longitude: -82.4719,
    image_url: img(2),
    amenities: ["Hardwood Floors", "Patio", "Air Conditioning", "Laundry in Building", "Pet Friendly", "Bike Storage"],
  },
  {
    title: "Channelside 2BR with Water Views",
    description: "Upscale two-bedroom in Tampa's Channelside District with views of the cruise ship terminals and Hillsborough Bay. Concierge, heated pool, and walking distance to Amalie Arena.",
    address: "107 Harbour Place Dr",
    city: "Tampa", state: "Florida", zip: "33602",
    price: 3500, bedrooms: 2, bathrooms: 2, sqft: 1200,
    latitude: 27.9428, longitude: -82.4480,
    image_url: img(3),
    amenities: ["Pool", "Gym", "Concierge", "In-Unit Washer/Dryer", "Parking", "Water Views", "Air Conditioning"],
  },
  {
    title: "Ybor City Loft Studio",
    description: "Hip studio loft in the historic Ybor City cigar district. Exposed brick, tin ceilings, and original iron columns. Walking distance to live music venues and the Saturday market.",
    address: "1600 E 8th Ave",
    city: "Tampa", state: "Florida", zip: "33605",
    price: 1550, bedrooms: 0, bathrooms: 1, sqft: 560,
    latitude: 27.9578, longitude: -82.4373,
    image_url: img(4),
    amenities: ["Hardwood Floors", "Air Conditioning", "Laundry in Building", "Bike Storage"],
  },
  {
    title: "San Marco 2BR Classic",
    description: "Spacious two-bedroom in Jacksonville's prestigious San Marco neighborhood. Original 1950s hardwood floors, updated baths, and a screened porch overlooking a quiet tree-lined street.",
    address: "1872 River Oaks Rd",
    city: "Jacksonville", state: "Florida", zip: "32207",
    price: 1900, bedrooms: 2, bathrooms: 1, sqft: 1100,
    latitude: 30.3014, longitude: -81.6477,
    image_url: img(5),
    amenities: ["Hardwood Floors", "Screened Porch", "In-Unit Washer/Dryer", "Air Conditioning", "Pet Friendly", "Parking"],
  },
  {
    title: "Riverside Arts Market 1BR",
    description: "Stylish one-bedroom in Jacksonville's Riverside neighborhood, blocks from the Riverside Arts Market and the St. Johns River. Updated kitchen and quartz counters throughout.",
    address: "2020 Park St",
    city: "Jacksonville", state: "Florida", zip: "32204",
    price: 1600, bedrooms: 1, bathrooms: 1, sqft: 670,
    latitude: 30.3212, longitude: -81.6846,
    image_url: img(6),
    amenities: ["Air Conditioning", "Laundry in Building", "Dishwasher", "Parking", "Pet Friendly"],
  },
  {
    title: "Las Olas Luxury 2BR",
    description: "Sophisticated two-bedroom in Fort Lauderdale's premier Las Olas corridor. Italian marble baths, chef's kitchen, and a wraparound balcony. Heated pool and valet parking.",
    address: "350 SE 2nd St",
    city: "Fort Lauderdale", state: "Florida", zip: "33301",
    price: 3900, bedrooms: 2, bathrooms: 2, sqft: 1300,
    latitude: 26.1214, longitude: -80.1410,
    image_url: img(7),
    amenities: ["Pool", "Gym", "Valet Parking", "In-Unit Washer/Dryer", "Concierge", "Air Conditioning", "Balcony"],
  },
  {
    title: "Victoria Park 1BR Bungalow",
    description: "Tropical one-bedroom bungalow in Fort Lauderdale's Victoria Park. Private fenced yard with a pool, lush landscaping, and a one-car garage. Minutes from the beach.",
    address: "618 NE 7th Ave",
    city: "Fort Lauderdale", state: "Florida", zip: "33304",
    price: 2500, bedrooms: 1, bathrooms: 1, sqft: 800,
    latitude: 26.1311, longitude: -80.1278,
    image_url: img(8),
    amenities: ["Pool", "Air Conditioning", "Parking", "In-Unit Washer/Dryer", "Pet Friendly", "Yard"],
  },
  {
    title: "St. Pete Beach 2BR Retreat",
    description: "Breezy two-bedroom apartment half a mile from St. Pete Beach. Plantation shutters, tile throughout, and a screened patio. Community pool and direct bike path to the beach.",
    address: "4240 Gulf Blvd",
    city: "St. Petersburg", state: "Florida", zip: "33706",
    price: 2700, bedrooms: 2, bathrooms: 2, sqft: 1040,
    latitude: 27.7208, longitude: -82.7357,
    image_url: img(9),
    amenities: ["Pool", "Air Conditioning", "Screened Porch", "Parking", "Pet Friendly", "Bike Storage"],
  },
  {
    title: "Downtown St. Pete 1BR",
    description: "Vibrant one-bedroom in downtown St. Pete's Central Arts District. Walking distance to the Dali Museum, craft beer bars, and Saturday Morning Market. Rooftop pool and dog walk.",
    address: "100 2nd Ave S",
    city: "St. Petersburg", state: "Florida", zip: "33701",
    price: 2200, bedrooms: 1, bathrooms: 1, sqft: 720,
    latitude: 27.7676, longitude: -82.6403,
    image_url: img(0),
    amenities: ["Pool", "Rooftop Deck", "Gym", "In-Unit Washer/Dryer", "Air Conditioning", "Dog Park", "Pet Friendly"],
  },
  {
    title: "Boca Raton Luxury 3BR",
    description: "Impeccable three-bedroom in a prestigious Boca Raton community. Private two-car garage, heated pool and spa, summer kitchen, and a spacious screened lanai.",
    address: "9100 W Palmetto Park Rd",
    city: "Boca Raton", state: "Florida", zip: "33428",
    price: 5800, bedrooms: 3, bathrooms: 3, sqft: 2200,
    latitude: 26.3683, longitude: -80.1289,
    image_url: img(1),
    amenities: ["Pool", "Gym", "Parking", "In-Unit Washer/Dryer", "Air Conditioning", "Screened Lanai", "Pet Friendly"],
  },
  {
    title: "Delray Beach 2BR Walk to Atlantic",
    description: "Gorgeous two-bedroom two blocks from Atlantic Avenue and the beach. Tropical landscaping, community pool, and outdoor grill area. Sought-after location in walkable Delray.",
    address: "220 NE 4th St",
    city: "Delray Beach", state: "Florida", zip: "33444",
    price: 2850, bedrooms: 2, bathrooms: 2, sqft: 1050,
    latitude: 26.4618, longitude: -80.0728,
    image_url: img(2),
    amenities: ["Pool", "Air Conditioning", "Laundry in Building", "Parking", "BBQ Area", "Pet Friendly"],
  },
  {
    title: "Tallahassee College Town Studio",
    description: "Affordable furnished studio near FSU and the Capitol complex. Ideal for students, interns, or legislative staffers. All utilities included, community pool and study lounge.",
    address: "510 W Tennessee St",
    city: "Tallahassee", state: "Florida", zip: "32304",
    price: 1100, bedrooms: 0, bathrooms: 1, sqft: 430,
    latitude: 30.4384, longitude: -84.2930,
    image_url: img(3),
    amenities: ["Pool", "Furnished", "Air Conditioning", "Laundry in Building", "Utilities Included"],
  },
  {
    title: "Fort Myers River District 1BR",
    description: "Charming one-bedroom in the Fort Myers River District, steps from First Street's galleries and waterfront restaurants. Updated kitchen, large balcony, and assigned covered parking.",
    address: "2220 First St",
    city: "Fort Myers", state: "Florida", zip: "33901",
    price: 1750, bedrooms: 1, bathrooms: 1, sqft: 690,
    latitude: 26.6406, longitude: -81.8723,
    image_url: img(4),
    amenities: ["Balcony", "Air Conditioning", "Parking", "Laundry in Building", "Pet Friendly"],
  },
  {
    title: "Naples Park Shore 2BR Retreat",
    description: "Pristine two-bedroom in Naples' prestigious Park Shore neighborhood. Steps from Venetian Village shops and the Gulf beach. Community pool, private beach access, and carport.",
    address: "4255 Gulf Shore Blvd N",
    city: "Naples", state: "Florida", zip: "34103",
    price: 4200, bedrooms: 2, bathrooms: 2, sqft: 1320,
    latitude: 26.2019, longitude: -81.8128,
    image_url: img(5),
    amenities: ["Pool", "Beach Access", "Air Conditioning", "Parking", "In-Unit Washer/Dryer", "Balcony"],
  },
  {
    title: "Hialeah Modern 2BR",
    description: "Brand new two-bedroom in Hialeah with a modern open-plan layout. Quartz counters, porcelain tile throughout, and a private patio. Easy access to the Tri-Rail commuter line.",
    address: "1230 W 49th St",
    city: "Hialeah", state: "Florida", zip: "33012",
    price: 2100, bedrooms: 2, bathrooms: 2, sqft: 960,
    latitude: 25.8576, longitude: -80.2781,
    image_url: img(6),
    amenities: ["Air Conditioning", "Patio", "Parking", "In-Unit Washer/Dryer", "Pool", "Pet Friendly"],
  },
  {
    title: "Clearwater Beach 1BR Steps from Sand",
    description: "Coveted beachfront building — this one-bedroom is just steps from the powdery white sands of Clearwater Beach. Saltwater pool, private beach access, and a large wrap-around balcony.",
    address: "715 S Gulfview Blvd",
    city: "Clearwater", state: "Florida", zip: "33767",
    price: 3100, bedrooms: 1, bathrooms: 1, sqft: 750,
    latitude: 27.9745, longitude: -82.8301,
    image_url: img(7),
    amenities: ["Pool", "Beach Access", "Air Conditioning", "Balcony", "Parking", "In-Unit Washer/Dryer"],
  },
  {
    title: "Pensacola Downtown 1BR Loft",
    description: "Historic brick loft in downtown Pensacola. Original timber beams, exposed brick, and an updated industrial kitchen. Walking distance to Seville Quarter and the downtown waterfront.",
    address: "312 S Palafox St",
    city: "Pensacola", state: "Florida", zip: "32502",
    price: 1450, bedrooms: 1, bathrooms: 1, sqft: 740,
    latitude: 30.4090, longitude: -87.2169,
    image_url: img(8),
    amenities: ["Hardwood Floors", "Air Conditioning", "Laundry in Building", "Bike Storage", "Pet Friendly"],
  },
  {
    title: "Gainesville University 2BR",
    description: "Spacious two-bedroom near the University of Florida campus and Butler Plaza. Renovated interior with granite counters and stainless appliances. Screened patio and covered parking.",
    address: "3800 SW 34th St",
    city: "Gainesville", state: "Florida", zip: "32608",
    price: 1650, bedrooms: 2, bathrooms: 2, sqft: 1010,
    latitude: 29.6407, longitude: -82.3889,
    image_url: img(9),
    amenities: ["Pool", "Air Conditioning", "Screened Porch", "Parking", "In-Unit Washer/Dryer", "Pet Friendly"],
  },
];

async function seed() {
  console.log(`Inserting ${listings.length} listings…`);

  const { data, error } = await supabase
    .from("listings")
    .insert(listings)
    .select("id, title, city, state");

  if (error) {
    console.error("❌ Supabase error:", error.message);
    console.error("Details:", error.details);
    process.exit(1);
  }

  console.log(`✅ Inserted ${data.length} listings:`);
  data.forEach(l => console.log(`  · [${l.state}] ${l.title} — ${l.city}`));
}

seed();
